### ISSUE TITLE
#nulldvachin

### ISSUE THREAD

**Issue by lisanyan** [Mishiranu/Dashchan-Extensions#1]
I suck at intros..

В общем, если файл загружен на pomf.cat, то src получается вида 
//a.pomf.cat/plapla.webm (линк без протокола)
и в итоге аппендится к домену борды.
В массиве файла есть ключ external_upload (1/0), можно по нему проверять, и не аппендить линк или добавлять к нему протокол (e.g. "https:" + //a.pomf.cat/plapla.webm).

Еще в апи пару новых фич добавила
Удаление постов теперь может отдавать json, параметр ajax=1 в запрос

```
{
   "error" : {
      "1325" : "Неверный пароль для удаления.",
      "1327" : "Неверный пароль для удаления.",
      "1292" : "Неверный пароль для удаления.",
      "766" : "Неверный пароль для удаления."
   },
   "error_code" : 200
}
```

При успешном удалении вернет 
`{ "redir" : "/b/thread/num" }`
или если был удален тред
`{ "redir" : "/b/" }`

Еще желательно добавлять параметр parent с номером треда к delete task, если пост из треда удаляется, чтобы правильный редирект был.

Список борд теперь можно забирать по /board/api/getboards

Алсо, теги sup/sub в разметку можно добавить и инпут no_pomf (не грузить файлы на внешний сервер) в форму отправки (если не сложно).

**Comment by Mishiranu** [comment]
Вроде почти всё сделал, кроме двух вещей.

Во-первых, мне не очень нравится апи списка досок т. к. они не упорядочены. Правильно отдавать массив объектов с полями "board_name" и "title", например. Или на сервере в принципе не предусмотрен порядок досок, а на страницах доски вбиты вручную?

Во-вторых, поддержку "no_pomf" добавить не получится. Модули тут бессильны, новые кнопочки-галочки можно добавлять только на стороне приложения. Я бы подумал насчёт добавления в приложение, но фича уж больно уникальная и, по моему мнению, не сильно востребованная.

**Comment by lisanyan** [comment]
Массив сейчас переделаю с сортировкой и ключами board_desc/board_name. На страницах вручную забиты, руки никак не дойдут допилить динамическую подгрузку досок.

Окей, no_pomf - не критично.

**Comment by Mishiranu** [comment]
Так доски по алфавиту сортируются? Просто сортировать json-объект нет никакого смысла, потому что он в принципе не может быть упорядоченным, в любом случае стоит сделать массив.

**Comment by lisanyan** [comment]
Да. Действительно, но пусть будет, ибо мне один аргумент достаточно было json энкодеру скормить.

Готово, сейчас нормально?

**Comment by Mishiranu** [comment]
У меня что-то сайт вообще отвалился.

**Comment by lisanyan** [comment]
Сейчас вроде открывается, у хостера что-то с IO, диски оче медленно работают.

**Comment by Mishiranu** [comment]
Так что, думаешь объектом всё таки оставить? А то я что-то не вижу разницы по сравнению с прошлым разом, лол.

**Comment by lisanyan** [comment]
Не. Т.е. мне просто `data` массивом сделать?

**Comment by Mishiranu** [comment]
Да, всё верно. И к каждому элементу массива добавить ещё поле кода доски.

**Comment by lisanyan** [comment]
Интернеты отвалились :\

Что-то вроде

```
   "data" : [
      {
         "board_desc" : "Чятик для двоих",
         "board_key" : "a",
         "board_name" : "Аниме"
      },
    ]
```

получилось

**Comment by lisanyan** [comment]
Или так сделать?

```
   "data" : [
      "a" : {
         "board_desc" : "Чятик для двоих",
         "board_key" : "a",
         "board_name" : "Аниме"
      },
    ]
```

**Comment by Mishiranu** [comment]
Первый вариант лучше. Короче, как сейчас — лучше всего.

**Comment by lisanyan** [comment]
Done.

**Comment by Mishiranu** [comment]
Ок, тогда я всё сделал, сейчас обновлю.

**Comment by lisanyan** [comment]
Сек

**Comment by lisanyan** [comment]
Я думаю возврат апи удалялки тоже массивом сделать

**Comment by Mishiranu** [comment]
Да это уже необязательно.

**Comment by lisanyan** [comment]
Ну ладно, тогда как есть оставлю. Спасибо.

**Comment by Mishiranu** [comment]
Просто я уже закоммитил релиз, лол. Я могу откатить, конечно, просто стоит ли?

**Comment by lisanyan** [comment]
Ну если его легче парсить будет, то думаю да. Или инкремент версии сделать до 1.4 лучше

Алсо, delete еще это выдать может, 

```
Тред закрыт
Неправильный IP - (посты можно удалять без пароля, если айпи клиента совпадает с ip поста)
Пост протух.
```

Или необязательно хандлить все сообщения?

**Comment by Mishiranu** [comment]
Ну, мне разницы-то нет, но если хочешь сделать чтобы типа "нормально" было — давай. Выпущу как 1.4 потом.

Обработку этих сообщений тоже добавлю.

**Comment by Mishiranu** [comment]
Только лучше не так, как сейчас

```
{
   "error" : [
      {
         "380" : "Неверный пароль для удаления."
      }
   ],
   "error_code" : 200
}
```

а как-то так например:

```
{
   "error" : [
      {
         "post_id": "380",
         "reason": "Неверный пароль для удаления."
      }
   ],
   "error_code" : 200
}
```

**Comment by Mishiranu** [comment]
Кстати, вообще для апи рекомендую `Content-Type` отдавать `application/json; charset=utf-8` вместо простого `application/json`.

**Comment by lisanyan** [comment]
Оке, просто переписывать историю коммитов не есть хорошо, если форки есть :D
Теперь такой вывод (наверное еще больше complicated :\ )

```
"error" : [
      {
         "error_msg" : "Неверный пароль для удаления.",
         "post" : "1331"
      },
   ],
```

Поправила Content-Type

**Comment by lisanyan** [comment]
Теперь post_id/reason в объекте

**Comment by lisanyan** [comment]
Алсо, клиент куки сохраняет которые с ответом сервера после постинга прилетели?

**Comment by Mishiranu** [comment]
Нет. Что за куки и для чего они?

**Comment by lisanyan** [comment]
name, если в нейме есть трип который есть в дб, то можно постить на любых досках с неймом и без капчи (что-то вроде пасскодов, лол).

**Comment by Mishiranu** [comment]
Не понял, а почему эта кука после постинга появляться должна?

**Comment by lisanyan** [comment]
Header set-cookie в ответе task=post.

**Comment by Mishiranu** [comment]
Не, как куки работают я знаю. Я просто не могу понять, что она делать должна. Имя-то везде можно использовать, кроме некоторых досок, да и капчи тоже я нигде не видел.

**Comment by lisanyan** [comment]
/api/checkconfig проверяет через нее есть ли "специальный" трипкод из дб в имени, и возвращает captcha=0 и names_allowed=1 даже если постинг с неймом в конфиге отключен.

Но наверное нет смысла ковыряться с ней, оверкилл.

Капча есть у всех кроме /RU UA BY KZ EU/

**Comment by Mishiranu** [comment]
Так погоди, эта кука же просто хранит последнее введённое имя, так? И при наличии куки просто немного меняется конфиг? То есть фактически мне не надо даже сохранять куку, а просто можно использовать введённое имя?

Про капчу я вообще забыл, что она есть, лол, а ведь она реализована в модуле.

**Comment by lisanyan** [comment]
Йеп. Хмм, можно использовать последнее введенное имя, если оно где-то сохраняется, если надо могу инпут name к checkconfig добавить вместо печеньки.

**Comment by Mishiranu** [comment]
Не, не обязательно, я без проблем смогу сделать чтобы с кукой передавалось.

**Comment by Mishiranu** [comment]
А такой вопрос: например, я ввожу имя, которое есть в базе, отправляю пост, иду в d, ввожу там другое имя, снова отправляю пост. Таким образом, кука заменится, но пост отправится со вторым введённым именем?
Вообще было бы хорошо, если бы для тестирования для меня было бы заведено такое имя, хотя бы на время.

**Comment by lisanyan** [comment]
Пост отправится только если введено имя, которое в дб, иначе просто "Аноним". В функции постинга тоже проверка есть.

Оки, вот тестовый трип #TestCode

**Comment by Mishiranu** [comment]
Я просто думаю, может, в таком случае, стоит оформить это как авторизацию? Дашчан поддерживает авторизацию пользователей.

**Comment by lisanyan** [comment]
Хм, можно. Может тогда отдельную куку для этих целей прикрутить (что-то вроде auth, трипкод прошел проверку -> сохранить этот трип в auth и проверять уже по куке auth)?

Имхо так лучше будет.

**Comment by Mishiranu** [comment]
Да не обязательно, можно как есть оставить. Я вот так хочу сделать:
1. В настройках надо ввести свой трипкод. Если он проходит авторизацию — сохраняю его.
2. При открытии окна постинга проверяется наличие сохранённого в настройках трипкода. Если он есть — разрешаю отображение поля ввода имени.
3. При отправке поста этот трипкод автоматически склеивается с введённым именем.

**Comment by lisanyan** [comment]
Да я все равно уже re-implementing this. Добавлю в чекконфиг инпут с auth и в ответ поле вроде check_success.

Мне идея со склеиванием не оче нравится, что если я введу другой трип в поле нейма?

И 2 пункт немного переделать можно будет
- Отправляем checkconfig с инпутом (или кукой?) auth который содержит трип из настроек при обновлении доски.
  если names_allowed отдает 1 то поле ввода же само включается?

**Comment by Mishiranu** [comment]
> Мне идея со склеиванием не оче нравится, что если я введу другой трип в поле нейма?

`if (name.indexOf('#') == -1) name += '#' + authorizedTripcode;`

То есть теперь авторизация будет возможна отдельно от трипкода? Это, конечно, лучше.

**Comment by lisanyan** [comment]
Да.

Кука auth с трипом должна будет отправляться чекконфигу и функции постинга/удаления, сможешь реализовать?

**Comment by Mishiranu** [comment]
Смогу. А с удалением что? Типа пароль не нужен?

**Comment by lisanyan** [comment]
Удаление без задержки как вариант.

Может функцию авторизации отдельно добавить? пока код еще редактирую

**Comment by lisanyan** [comment]
Готово

/api/authorize?auth=trip, только trip должен быть urlencoded, task=post с правильным трипом также авторизует (отдает куки auth)
/api/checkconfig теперь содержит поле authorized в объекте config

**Comment by Mishiranu** [comment]
Лол, заодно обнаружил баг в приложении, в определённый момент ссылка декодируется и вся часть ссылки начиная с # считается фрагментом ссылки и не отправляется на сервер. Буду использовать пост-запрос, но баг устраню в следующей версии на будущее, разумеется.

**Comment by lisanyan** [comment]
Great.

**Comment by Mishiranu** [comment]
Так, к authorize нельзя пост-запросом обращаться, только гет?

**Comment by lisanyan** [comment]
Хм, вроде фильтра никакого на нем нет, так что можно.

**Comment by Mishiranu** [comment]
У меня чего-то не получается, выдаёт html страницу.

**Comment by lisanyan** [comment]
Так должно работать

```
<form id="postform" action="/wakaba.pl" method="post" enctype="multipart/form-data">
<input type="hidden" name="section" value="b">
<input type="hidden" name="task" value="json">
<input type="hidden" name="json" value="authorize">
<input type="text" name="auth" value="">
</forrm>
```

**Comment by Mishiranu** [comment]
Лол, а я шлю запрос на `b/api/authorize`.
Попробую тогда.

**Comment by lisanyan** [comment]
rewrite правило /api/ не работает с POST запросами
Оки

**Comment by lisanyan** [comment]
Well, параметр task тут не нужен.

**Comment by Mishiranu** [comment]
`section`, как оказывается, тоже. Ну это логично.

**Comment by lisanyan** [comment]
`section == b`, если нет аргумента.

**Comment by Mishiranu** [comment]
Всё, выпустил 1.4 с поддержкой авторизации.

**Comment by lisanyan** [comment]
Thanks again

**Comment by lisanyan** [comment]
Хм, а флаги стран прикрутить можно? Поля location, location_full в объекте поста, geoip_enabled в конфиг объекте, флаги лежат в /img/flags/ (файлнеймы капсом)

И еще auth cookie добавить к /api/thread,/api/threads (клиент же оттуда берет конфиг?) и проверку c authorizedTripcode != null можно убрать тогда, если names_allowed будет отдавать 1.

И тут вроде должно быть
`int attachmentCount = configObject.optInt("max_files", 4);`
вместо
`int attachmentCount = configObject.optInt("max_res", 4);`

**Comment by Mishiranu** [comment]
> Хм, а флаги стран прикрутить можно?

Готово

> и проверку c authorizedTripcode != null можно убрать тогда

Я, помню, специально делал именно так, как это сделано сейчас, но это было когда ещё кука auth не поддерживалась. Сейчас, наверное, можно убрать эту проверку.

> И тут вроде должно быть

Точно, невнимательно копировал же. Сделал нормально.

Всё, заливать обновление, или ещё что-то?

**Comment by lisanyan** [comment]
Спасибо, пока вроде всё, заливай.

**Comment by Mishiranu** [comment]
Залил.

**Comment by lisanyan** [comment]
Оки.

**Comment by lisanyan** [comment]
Можешь допилить хандлер чтобы показывал ip/причину/срок когда истекает(0 - never)?

Новый апи для банов (return функции поста)

бан as-сети

```
{
   "banned" : 1,
   "bans" : [
      {
         "showmask" : 0,
         "ip" : "94.242.58.252",
         "reason" : "AS Network is banned",
         "expires" : "0"
      }
   ],
   "error" : "Бан :&lt;",
   "error_code" : 200
}
```

обычный ip-бан

```
{
   "banned" : 1,
   "bans" : [
      {
         "network" : "94.242.58.252",
         "showmask" : 0,
         "ip" : "94.242.58.252",
         "reason" : "test",
         "setbits" : 32,
         "expires" : "1468527252"
      }
   ],
   "error" : "Бан :&lt;",
   "error_code" : 200
}
```

бан dnsbl

```
{
   "banned" : 1,
   "bans" : [
      {
         "showmask" : 0,
         "ip" : "176.10.104.240",
         "reason" : "This IP was listed in tor.dnsbl.sectoor.de blacklist!",
         "expires" : 0
      }
   ],
   "error" : "Найдена прокси.",
   "error_code" : 200
}
```

и еще печеньку auth добавь к /api/post.

**Comment by Mishiranu** [comment]
Готово. Обновлять?

**Comment by lisanyan** [comment]
Сек, еще вопрос, можно у Icon менять размер шрифта/позицию текста или это в самом клиенте захардкожено?

**Comment by Mishiranu** [comment]
Не понял. У иконки поста? Что за размер шрифта и позиция текста?

**Comment by lisanyan** [comment]
У меня на старой мобилке с низкоразрешением не влезала геоинфа в диалоге по клику на флаг  (получалось что-то вроде RUSSIAN FEDERATION, SAINT PETERS), пришлось урезать строку до вида RU, Saint Petersburg.

Алсо, функция поста не всегда отдает поле banned, не будет exception из-за того что его нет, или лучше добавить его во все ошибки?

**Comment by Mishiranu** [comment]
А, да, текст должен быть коротким и влезать в 1 строку. Оно на что-то более серьёзное не было рассчитано.

**Comment by Mishiranu** [comment]
> Алсо, функция поста не всегда отдает поле banned, не будет exception из-за того что его нет, или лучше добавить его во все ошибки?

`int banned = jsonObject.optInt("banned", 0);`

Не будет. Если оно отсутствует или оно не преобразуется в число — вернёт 0.

**Comment by lisanyan** [comment]
Тогда окей.

Поиск по борде еще можно прикрутить? /api/search
Параметры

```
find - строка для поиска
op - искать только в оп-постах
comment - поиск по тексту в посте (должен быть 1)
subject - поиск по теме
```

**Comment by Mishiranu** [comment]
Тоже готово.

**Comment by lisanyan** [comment]
Thx~

Обновляй.

**Comment by lisanyan** [comment]
#crash
В общем, если я отключаю флажки на борде, и рефрешу полностью тред (который закешировался с флажками), то клиент вылетает.

```
Device: Sony Ericsson hallon (MT15i)
SDK: 18 (4.3.1)
Application: 1031 (2.8.0)
----------------------------------------
java.lang.RuntimeException: An error occured while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:299)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
    at java.util.concurrent.FutureTask.run(FutureTask.java:239)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
    at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NullPointerException
    at chan.content.model.Post.contentEquals(Post.java:559)
    at chan.content.model.Posts.pendingMerge(Posts.java:339)
    at com.mishiranu.dashchan.async.ReadPostsTask.doInBackground(ReadPostsTask.java:184)
    at com.mishiranu.dashchan.async.ReadPostsTask.doInBackground(ReadPostsTask.java:1)
    at android.os.AsyncTask$2.call(AsyncTask.java:287)
    at java.util.concurrent.FutureTask.run(FutureTask.java:234)
    ... 3 more
```

**Comment by Mishiranu** [comment]
Да, глупая ошибка. Попробуй удали пока что тред из кэша (или вообще кэш очисти), а я сейчас исправлю.

**Comment by Mishiranu** [comment]
Это ошибка не в модуле, а в клиенте, так что только с его обновлением что-то изменится.

**Comment by lisanyan** [comment]
Оки.

**Comment by Mishiranu** [comment]
Выключи флажки в b, кстати, хотя бы проверю, исправил ли я баг.

**Comment by lisanyan** [comment]
Done.

**Comment by Mishiranu** [comment]
Эх, я только подумал, что мне будет проще локально у себя их просто убрать для теста, и удалил прошлое сообщение... Ну да ладно.

**Comment by wakaber** [comment]
Можешь авторизоваться с #TestCode и проверить в d например, потом разлогиниться и сделать рефреш.

**Comment by Mishiranu** [comment]
Да я уже всё проверил.
На будущее — лучше создай issue у самого проекта, если подобный вылет происходит, расширение само по себе не может приводить к вылету (нет, ну может конечно, если постараться), а если всё таки приводит — это баг клиента.

**Comment by lisanyan** [comment]
Получилось пофиксить?

Alrighty.

**Comment by Mishiranu** [comment]
Да, получилось.

**Comment by wakaber** [comment]
API update

Новые поля в конфиге
```
max_comment_length //Maximum number of characters in a comment
max_field_length //Maximum number of characters in subject, name, and email
default_name //Дефолтный нейм (аноним итд)
```

Печенька ```auth``` переименована в ```wakaauth```

Алсо, категории борд можешь прикрутить? Только я не знаю как их лучше реализовать, сейчас есть поле board_cat в объекте массива с досками .

**Comment by lisanyan** [comment]
API update

Новые поля в конфиге

```
max_comment_length //Maximum number of characters in a comment
max_field_length //Maximum number of characters in subject, name, and email
default_name //Дефолтный нейм (аноним итд)
```

Скорость борды (постов в час) - поле board_speed в boardinfo.

Печенька `auth` переименована в `wakaauth`

Алсо, категории борд можешь прикрутить? Только я не знаю как их лучше реализовать (чтобы динамически подгружалось), сейчас есть поле board_cat в объекте массива с досками.

Могу добавить пару строк, чтобы делать сплит по "|" в массивы

```
"info" : {
     "category_order" : "Обсуждения|Общее|Японская культура",
     "board_order" : "a|b|d|diy|elf|h|l|mg|mu"
}
```

Или добавить сортированные массивы

```
"info" : {
      "category_array" : [
         "Обсуждения",
         "Общее",
         "Японская культура"
      ],
      "board_array" : [
         "a",
         "b",
         "d",
         "diy",
         "elf",
         "h",
         "l",
         "mg",
         "mu"
      ],
}
```

UPD: Welp, думаю оставлю массивы
UPD:  Алсо, добавь капкод мода

```
adminpost == 1 //capcode - Team
adminpost == 2 //capcode - Mod
```

**Comment by Mishiranu** [comment]
> max_comment_length

Точно максимальное число символов? Не байт?

**Comment by lisanyan** [comment]
Байт, но сейчас исправлю.

**Comment by Mishiranu** [comment]
> Печенька auth переименована в wakaauth

А `b/api/authorize` как работает? Его параметр тоже `wakaauth` называется или по прежнему `auth`?

**Comment by Mishiranu** [comment]
> Байт, но сейчас исправлю.

Лол, я сейчас в d пытался пост отправить, мне в качестве кода ошибки возвращалась длина строки. Я так и понял, что ты длину строки тестируешь.

**Comment by lisanyan** [comment]
> Лол, я сейчас в d пытался пост отправить, мне в качестве кода ошибки возвращалась длина строки. Я так и понял, что ты длину строки тестируешь.

Да, лол.

Done, теперь чекает по символам.

Параметр по прежнему auth называется.

**Comment by Mishiranu** [comment]
Готово всё. Обновлять?

**Comment by lisanyan** [comment]
Йеп.

**Comment by lisanyan** [comment]
Можешь альт. домен обновить?

02ch.info мертв, новый - buttflaps.pp.ua

**Comment by Mishiranu** [comment]
Готово.

**Comment by lisanyan** [comment]
Сменили движок на meguca (на тохочане тоже), соотвественно апи поменялся, можешь запилить?

Описание [здесь](https://github.com/bakape/meguca/blob/master/docs/json.md)
Алсо у объекта треда еще поля sticky и locked, но в доке не описаны.
